(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'true' is not defined"
p3
sS'layer'
p4
S'/home/joseph/BabbleBot/applications/BabbleBot/controllers/core.py'
p5
sS'code'
p6
S'<code object <module> at 0x7fc3043f6a30, file "/home/joseph/BabbleBot/applications/BabbleBot/controllers/core.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/joseph/BabbleBot/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/joseph/BabbleBot/applications/BabbleBot/controllers/core.py", line 77, in <module>\n  File "/home/joseph/BabbleBot/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/joseph/BabbleBot/applications/BabbleBot/controllers/core.py", line 37, in getComments\n    if group == true:\nNameError: global name \'true\' is not defined\n'
p11
s.