(dp1
S'output'
p2
S"<type 'exceptions.UnboundLocalError'> local variable 'groups' referenced before assignment"
p3
sS'layer'
p4
S'/home/joseph/BabbleBot/applications/BabbleBot/controllers/core.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f3ed80247b0, file "/home/joseph/BabbleBot/applications/BabbleBot/controllers/core.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/joseph/BabbleBot/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/joseph/BabbleBot/applications/BabbleBot/controllers/core.py", line 73, in <module>\n  File "/home/joseph/BabbleBot/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/joseph/BabbleBot/applications/BabbleBot/controllers/core.py", line 31, in guestCheck\n    return dict(auth=auth,groups=groups)\nUnboundLocalError: local variable \'groups\' referenced before assignment\n'
p11
s.